#!/bin/sh

name=$1
. "$HOME/$name.params"
echo Starting $CONTAINER_NAME
lxc-start -n "$CONTAINER_NAME"
if [ $? -ne 0 ]; then
	exit $?
fi
sleep 10
echo Starting build by $BUILD_USER in $CONTAINER_NAME
lxc-attach -n "$CONTAINER_NAME" -- /home/$BUILD_USER/blastem/build_nightly $BUILD_USER needsu 2>&1 > /tmp/build_${name}_out.log
result=$?
if [ $result -ne 0 ]; then
	echo Build falied with return code $result stopping $CONTAINER_NAME
	lxc-stop -n "$CONTAINER_NAME"
	exit $result
fi
echo "Build succeeded, stopping $CONTAINER_NAME"
lxc-stop -n "$CONTAINER_NAME"
. $HOME/remote.params
artifact=$(tail -n 1 /tmp/build_${name}_out.log)
echo "Uploaing $artifact to $REMOTE_HOST"
scp -i "$REMOTE_IDENT" "$HOME/.local/share/lxc/$CONTAINER_NAME/rootfs/home/$BUILD_USER/blastem/$artifact" $REMOTE_USER@$REMOTE_HOST:/home/$REMOTE_USER/nightlies
echo "Done"
