#!/bin/sh
name=$1

cd $HOME/blastem_win
hg revert -a
hg pull
hg up
rev=`hg summary |  sed -E -n 's/^parent: [^:]+:([^ ]+) .*$/\1/p'`
sed -i -E "s/(define BLASTEM_VERSION \"[^-]+)-pre\"/\1-pre-$rev\"/" blastem.c
export OS=Windows
./build_release > /tmp/build_${name}_out.log
result=$?
if [ $result -ne 0 ]; then
	echo Build falied with return code $result
	exit $result
fi
. $HOME/remote.params
artifact=$(tail -n 1 /tmp/build_${name}_out.log)
echo "Uploaing $artifact to $REMOTE_HOST"
scp -i "$REMOTE_IDENT" "$HOME/blastem_win/$artifact" $REMOTE_USER@$REMOTE_HOST:/home/$REMOTE_USER/nightlies
